from __future__ import annotations

from backend.app.schemas.research import ResearchRequest, Source
from backend.app.services.llm_service import LLMService


DISCLAIMER = (
    "This is an educational research report generated by an AI system and is not "
    "financial advice."
)


def synthesize_report(
    request: ResearchRequest,
    sources: list[Source],
    bull_case: str,
    bear_case: str,
    llm: LLMService,
) -> str:
    source_context = "\n".join(
        f"[{index}] {source.title} | {source.url} | {source.content[:700]}"
        for index, source in enumerate(sources, start=1)
    )
    system = (
        "You are an investment committee chair producing a neutral, educational "
        "research report. Use only supplied evidence. Cite material claims with "
        "bracketed source numbers. If evidence is missing, say so. Do not present "
        "the report as financial advice."
    )
    user = f"""
Company: {request.company}
Ticker: {request.ticker}
Goal: {request.goal}

Bull case draft:
{bull_case}

Bear case draft:
{bear_case}

Sources:
{source_context}

Write a markdown report with these sections:
- Executive summary
- Business overview
- Recent developments
- Competitive landscape
- Bull case
- Bear case
- Key risks
- Metrics to watch
- Final neutral investment-style conclusion
- Source citations / references

Include this exact disclaimer near the top:
{DISCLAIMER}
"""
    report = llm.generate(system, user)
    if DISCLAIMER not in report:
        report = f"> {DISCLAIMER}\n\n{report}"
    references = "\n".join(
        f"[{index}] {source.title or 'Untitled source'} - {source.url}"
        for index, source in enumerate(sources, start=1)
    )
    if references and "## Source citations / references" not in report:
        report = f"{report.rstrip()}\n\n## Source citations / references\n\n{references}"
    elif references:
        report = f"{report.rstrip()}\n\n{references}"
    return report
